Use @staticmethod, add mutually exclusive flags
darkHarry/yts-cli pull request #5
Opened 2020-03-12 22:37 UTC by philippeitis

Instead of == None, it is more idiomatic to use is None - this is good practice in general. 

If you specify the number of args for argparse, argparse will automatically create a list of the specified size - there is no need to check the length of the output. You can also use parser.add_mutually_exclusive_group() to create a mutually exclusive group, of which only one option can be specified, which helps simplify your Arguments class a lot.

If you use a number of methods together, such as getting the title, page, and format of a given movie, it may be better to just put them into a single function - the user probably doesn't care about the page, which is raw data, but is interested in knowing the title and available formats of their movie.

For functions that should belong inside a class but don't need the classes' fields (eg. self is never used), it's often a good idea to use @staticmethod to enforce this - it helps avoid potential bugs from modifying the class, and it allows the method to be used as a class level method - eg. YTS.static_method(arg1, arg2), without having to instantiate a YTS object.

I also made use of __getitem__ for Arguments, which defines how Arguments["a"] behaves - so we can now directly call args["p"] without having to specify args.arguments["p"], which looks strange if it's already an Arguments class. Alternatively, by using @staticmethod, we could also call Arguments.get_cli_arguments() and avoid creating an Argument object altogether.

2020-03-19 13:45 UTC, darkHarry requested changes
Thanks for adding the static methods. It simplifies the readability and optimizes the code. I'll have to redesign the YTS class with static methods and instance methods which would make much more sense. If you like to do it then let me know. : )

It's a very small thing but can you group all the static methods under the UTIL FUNCTIONS comment and also rename the comment to be STATIC METHODS on line [119](https://github.com/philippeitis/yts-cli/blob/a8b79be9b61a77fdd60c4d01c4f4437aae6af4a5/yts/yts.py#L119)?

2020-03-19 13:45 UTC, darkHarry commented on yts/yts.py
> +        flags = parser.add_mutually_exclusive_group("Select one option for downloading.", required=True)
```suggestion
        flags = parser.add_mutually_exclusive_group(required=True)
```
It takes only a single argument.

2020-03-19 13:45 UTC, darkHarry commented on yts/yts.py
> +        res = make_request(self.url)
Change the `res = self.make_request(url)` to `res = make_request(url)`.
Link: https://github.com/philippeitis/yts-cli/blob/a8b79be9b61a77fdd60c4d01c4f4437aae6af4a5/yts/yts.py#L96

2020-03-19 13:45 UTC, darkHarry commented on yts/yts.py
> +    @staticmethod
Remove the `@staticmethod` and add `self` for now as print_formats uses get_movie_data instance method.
I'll redesign the YTS class with static methods. : )

2020-03-19 18:54 UTC, philippeitis commented
Changes have been made.

Also, as a general note - when commenting a function and how it works in python, you usually want to put the comments like so:

```
def fn(arg1, arg2):
     """
     documentation on how fn works
     
     (Optionally - formatting varies)
     arg1 - details about arg1
     arg2 - details about arg2
     returns - what fn returns
     """
```

This is also helpful as it allows using help(fn) to get the documentation, and can be used in combination with things like Sphinx to automatically generate a webpage with documentation, although this requires a bit of specific formatting. Comments with `#` are best used when documenting specific things inside the function.

I've included a link with more information:
https://docs.python-guide.org/writing/documentation/

2020-03-20 13:54 UTC, darkHarry approved these changes
LGTM : )

Thanks for the comment documentation info. I'll add that.

2020-03-20 13:55 UTC, merged